pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    tools {
        maven 'maven-3.9'
    }    
    stages {
        stage('Build') {
            steps {
                 bat 'echo Build successful!'
            }
        }
        stage('Test') {
            steps {
                bat 'echo All tests passed!'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                bat 'echo Deployed successfully!' 
            }
        }
    }
}
